version: '3'

services:
  robot-framework:
    # image: ${ROBOT_IMAGE_NAME}
    container_name: 'netapp_robot'
    restart: 'always'
    build:
      context: .
      dockerfile: ./tools/Dockerfile
    volumes:
      - ../capif_callback_server:/opt/robot-tests/capif-callback
      - ../nef_callback_server:/opt/robot-tests/nef-callback
      - ../pythonnetapp:/opt/robot-tests/pythonnetapp
      - ../evolved5g:/opt/robot-tests/pythonnetapp/evolved5g
      - ./tests:/opt/robot-tests/tests/
      - ./libraries:/opt/robot-tests/libraries/
      - ./resources:/opt/robot-tests/resources/
      - ./results:/opt/robot-tests/results/
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
      #     - ./${NETAPP_NAME}/capif_callback_server:/opt/robot-tests/capif-callback
      # - ./${NETAPP_NAME}/nef_callback_server:/opt/robot-tests/nef-callback
      # - ./${NETAPP_NAME}/pythonnetapp:/opt/robot-tests/pythonnetapp
