apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot-deployment
  labels:
    app: dockerhub.hi.inet/dummy-netapp-testing/robot-test-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robot-framework
  template:
    metadata:
      labels:
        app: robot-framework
    spec:
      containers:
      - name: robot-framework
        image: dockerhub.hi.inet/dummy-netapp-testing/robot-test-image
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /opt/robot-tests/tests
          name: test-volume
        - mountPath: /opt/robot-tests/results
          name: result-volume
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: ./tests
          # this field is optional
          type: Directory
      - name: result-volume
        hostPath:
          # directory location on host
          path: ./results
          # this field is optional
          type: Directory